spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/database-cache-postgresql
    username: DB_USERNAME
    password: DB_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis